autorization and autentication
tstepnik/planner pull request #1
Opened 2020-04-12 19:53 UTC by tstepnik

Autorization has working but i have to add role through id, findbyrole is not workin and i don't know why.
Autentication work.
Encoding and matchin also.

Closes #10 
Closes #3

2020-04-14 00:44 UTC, rbobko93 requested changes

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/PlannerApplication.java
> +    private void init(){
It might be useful to move it to different class or sql file in the future, so it won't be added from the code. Let's add todo reminding us about this.

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/RegistrationController.java
> +    public ResponseEntity<?> registerUser(@RequestBody User user){
Add type to ResponseEntity.

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/RegistrationController.java
> +        return new ResponseEntity<>(user, HttpStatus.CREATED);
What is registering fails? You still will return status CREATED?

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +@EnableGlobalMethodSecurity(prePostEnabled = true)
This annotation shouldnt be here. It is global(for the whole app) and should be in security confuration class. You shoul also read about it. What it does, etc.

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +    @GetMapping("/me")
Also it is worth prepending every endpoint with `/api`. It is good rest apps practise.

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +        return userRepository.findByUserName(login).orElseThrow(() -> new EntityNotFoundException("User not found"));
Dont use repo inside of Controller. Controller should only have access to Service class.

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +        return userRepository.findByUserName(login).orElseThrow(() -> new EntityNotFoundException("User not found"));
What happens when exception is thrown? What http status is returned?

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +        Optional<User> currentUser = userRepository.findById(id);
All of this code should be in a service.

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +        Optional<User> user = userRepository.findById(id);
Same here. This code should be in a service. No business logic in controllers.

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +    public ResponseEntity<?> deleteUser(@PathVariable("id")Long id){
Add return type.

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +    public ResponseEntity<?> updateUser(@RequestBody User user, @PathVariable("id") long id) {
Add return type. Dont use `ResponseEntity<?>`

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/domain/Role.java
> +    String description;
Description is enum as a string thus I don't think we need it at all.

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/domain/User.java
> +    public User() {
Move constructors below fields!

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/domain/User.java
> +    @Column(name = "username")
Why did you change column name? Hibernate deals with it on its own.

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/domain/User.java
> +    @Column(name = "username")
Also I would prefer `login` but it's your choice.

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/exceptions/CustomErrorType.java
> +public class CustomErrorType extends RuntimeException {
That doesn't make sense. You extended one generic exception type to create other generic exception. When creating new exceptions their name should be describing specific problem. Yours does not.

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/exceptions/EmailAlreadyExistException.java
> +public class EmailAlreadyExistException extends RuntimeException {
I left you comments about this name in previous repository.

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/exceptions/UserAlreadyExistException.java
> +public class UserAlreadyExistException extends RuntimeException {
Bad name.

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/exceptions/UserNotExistException.java
> +public class UserNotExistException extends RuntimeException {
Bad name.

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/repository/UserRoleRepository.java
> +    UserRole findByRole(String role);
Why one method returns optional and the other doesn't?

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/security/SecurityConfig.java
> +                .antMatchers("/").permitAll()
Same url twice in the config.

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/security/SecurityConfig.java
> +                .antMatchers("/", "/h2-console/**").permitAll()
Remember that now everybody has access to your DB.

2020-04-14 00:44 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/security/auth/CustomAuthenticator.java
> +            throw new RuntimeException("Bad credentials");
Dont throw Runtime.

2020-04-14 16:27 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/controller/RegistrationController.java
> +        return new ResponseEntity<>(user, HttpStatus.CREATED);
i added "if" statement with BAD_REQUEST return.

2020-04-14 21:06 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/repository/UserRoleRepository.java
> +    UserRole findByRole(String role);
I don't know why I did that :D Probably because I still don't feel comfortable with optionals.

2020-04-14 21:08 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/security/SecurityConfig.java
> +                .antMatchers("/", "/h2-console/**").permitAll()
I added TODO comment

2020-04-14 21:08 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/security/auth/CustomAuthenticator.java
> +            throw new RuntimeException("Bad credentials");
So what else and what's wrong with runtime ?

2020-04-15 13:29 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/PlannerApplication.java
> +                              @Lazy PasswordEncoder passwordEncoder) {
Why is password encoder lazy?

2020-04-15 13:29 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/PlannerApplication.java
> +    @Autowired
What is this annotation doing here? Just chilling?

2020-04-15 13:29 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/RegistrationController.java
> +    public ResponseEntity<User> registerUser(@RequestBody User user){
Currently we are returning User object with it's ID, password, etc. Let's create DTO for this object and use it here. Remind me on our lesson to talk about this topic

2020-04-15 13:29 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/RegistrationController.java
> +        return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
Code formatting.

2020-04-15 13:29 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
return empty list if no users were found. In this case it is not an error because client is not asking for a specific resource rather than list of resources.

2020-04-15 13:29 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/RegistrationController.java
> +        return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
Add todo here to remove once we add exception handler.

2020-04-15 13:29 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +        return new ResponseEntity<>(user.get(), HttpStatus.OK);
there is a shorter version. ResponseEntity.ok(user.get());

2020-04-15 13:42 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/PlannerApplication.java
> +                              @Lazy PasswordEncoder passwordEncoder) {
Because I use this bean also in security clasees and registration service so spring desn't know which passwordencoder use first.

2020-04-15 13:43 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/PlannerApplication.java
> +    @Autowired
haha i removed it in last commit, check if you are in last one ;)

2020-04-15 13:48 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +        return new ResponseEntity<>(user.get(), HttpStatus.OK);
done.

2020-04-15 13:50 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/controller/RegistrationController.java
> +        return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
done.

2020-04-15 13:52 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
Collections.emptyList() is fine ?

2020-04-15 13:53 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/controller/RegistrationController.java
> +        return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
Done.

2020-04-15 14:46 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/PlannerApplication.java
> +                              @Lazy PasswordEncoder passwordEncoder) {
That doesn't make sense. Do you have multiple password encoders in the app?

2020-04-15 14:47 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
No, just return what service is returning.

2020-04-15 14:54 UTC, rbobko93 requested changes

2020-04-15 14:54 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +    public static final Logger logger = LoggerFactory.getLogger(UserController.class);
why is it public?

2020-04-15 14:54 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +        Optional<User> updateUser = Optional.ofNullable(userService.updateUser(user, id));
```suggestion
        Optional<User> updatedUser = Optional.ofNullable(userService.updateUser(user, id));
```

2020-04-15 14:54 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +        if (updateUser.isEmpty() || !updateUser.isPresent()) {
What is the difference between isEmpty and !isPresent?

2020-04-15 14:54 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +            return new ResponseEntity<User>(updateUser.get(), HttpStatus.NOT_FOUND);
This doesnt make sense.

2020-04-15 14:54 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +            return new ResponseEntity<User>(updateUser.get(), HttpStatus.NOT_FOUND);
When there is no updated user you return it and return status not found? Also status is not right.

2020-04-15 14:54 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +            return new ResponseEntity<User>(updateUser.get(), HttpStatus.NOT_FOUND);
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

2020-04-15 14:54 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +    public ResponseEntity<User> deleteUser(@PathVariable("id") Long id) {
Bad return type.

2020-04-15 14:54 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/domain/Task.java
> +    public Task() {
Where should constructor be?

2020-04-15 14:54 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/domain/Task.java
> +    User user;
Where is access modifier?

2020-04-15 14:54 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/security/SecurityConfig.java
> +                .antMatchers("/api").permitAll()
Why are you allowing everyobdy access to `/api`?

2020-04-15 15:05 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/PlannerApplication.java
> +                              @Lazy PasswordEncoder passwordEncoder) {
No i have only one bean and few autowierd. When I had had that problem I was looking for solution and find one with @Lazy adnotation, code is workind so I didn't supose it was wrong.

2020-04-15 15:07 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +    public static final Logger logger = LoggerFactory.getLogger(UserController.class);
I even don't need that field, i removed it.

2020-04-15 15:08 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
ok.

2020-04-15 15:11 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +        if (updateUser.isEmpty() || !updateUser.isPresent()) {
heh i know it's stupid, I just try to figure it out how to catch some exception because if something is wrong i get differents statuses as 500 but never NOT_FOUD. And I don't know how to change it.

2020-04-15 15:14 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/domain/Task.java
> +    public Task() {
He will has never learnt....

2020-04-15 15:15 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/security/SecurityConfig.java
> +                .antMatchers("/api").permitAll()
Because everyone should have acess to /api/register ?

2020-04-15 16:27 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +    public ResponseEntity<User> deleteUser(@PathVariable("id") Long id) {
"Void" is correct one ?

2020-04-17 01:38 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/PlannerApplication.java
> +                              @Lazy PasswordEncoder passwordEncoder) {
I am not saying it is wrong. I want to know the reason why you used it and for now I still didn't get the answer. What was the problem?

2020-04-17 01:39 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +        if (updateUser.isEmpty() || !updateUser.isPresent()) {
You still didnt answer my question.

2020-04-17 01:39 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +    public ResponseEntity<User> deleteUser(@PathVariable("id") Long id) {
Yes.

2020-04-17 01:40 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/security/SecurityConfig.java
> +                .antMatchers("/api").permitAll()
Then allow access to this specific endpoint and not `/api`. 
`/api != /api/register`

2020-04-17 01:42 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +            return new ResponseEntity<User>(updateUser.get(), HttpStatus.NOT_FOUND);
You still didnt change the status you return.

2020-04-17 01:42 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/domain/Task.java
> +   private User user;
Formatting.

2020-04-17 07:47 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +        if (updateUser.isEmpty() || !updateUser.isPresent()) {
Practically there is no difference.

2020-04-17 07:59 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/PlannerApplication.java
> +                              @Lazy PasswordEncoder passwordEncoder) {
Without @Lazy addnotation in security class(CustomAuthenticator) i got BeanCurrentlyInCreationException. So I permised that I should add it everytime when I use the bean second time. I check it and there is no nessesary use it in PlannerApplication because of @PostConstruct addnotation but there is still nessesery use it in security class.

2020-04-17 08:01 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +            return new ResponseEntity<User>(updateUser.get(), HttpStatus.NOT_FOUND);
Is CONFLICT the correct one  ?

2020-04-17 13:19 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +        if (updateUser.isEmpty() || !updateUser.isPresent()) {
Exactly, so there is no point of using both of them.

2020-04-17 13:23 UTC, rbobko93 reviewed
It's annotation not addnotation. Install grammarly to check your spelling. Also, I dont know how but you tagged some guy in commit message by adding `@lazy` in it, lol

2020-04-17 13:23 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
>          return new ResponseEntity<>(HttpStatus.NO_CONTENT);
https://restfulapi.net/http-methods/#delete 

You have examples of good response statuses under this link.

2020-04-17 13:23 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/PlannerApplication.java
> +                               PasswordEncoder passwordEncoder) {
Why did you remove `@Lazy`?

2020-04-17 13:36 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/PlannerApplication.java
> +                               PasswordEncoder passwordEncoder) {
Yesterday you ashed me why I add @Lazy, just scroll up and find my answer or click that link: https://github.com/tstepnik/planner/pull/1#discussion_r410056825

2020-04-17 13:39 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/controller/UserController.java
>          return new ResponseEntity<>(HttpStatus.NO_CONTENT);
Can we just Postpone it? We were talking about do it later, i want merge branches and start doing other features.

2020-04-17 14:19 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/PlannerApplication.java
> +                               PasswordEncoder passwordEncoder) {
Cool, thats what I was talking about. Just couldn't find previous topic.

2020-04-17 14:21 UTC, rbobko93 requested changes

2020-04-17 14:21 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +        return new ResponseEntity<>(HttpStatus.NOT_FOUND);
I don't know where you read to change it to `not_found` but here is what I have seen in article I linked: `A successful response of DELETE requests SHOULD be HTTP response code 200 (OK)`

2020-04-17 14:22 UTC, rbobko93 requested changes

2020-04-17 14:22 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +    @PreAuthorize("hasRole('USER')")
I just noticed it. You are allowing any user to delete other users. Let's change it to `ROLE_ADMIN` for now.

2020-04-17 14:26 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +        return new ResponseEntity<>(HttpStatus.NOT_FOUND);
Yes, you're right. -,-

2020-04-18 09:00 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +        return new ResponseEntity<>(HttpStatus.NOT_FOUND);
But:

>  204 (No Content) if the action has been performed but the response does not include an entity

2020-04-18 09:01 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +        return new ResponseEntity<>(HttpStatus.NOT_FOUND);
and my response doesn't include entity, though.

2020-04-20 10:32 UTC, tstepnik commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +    @PreAuthorize("hasRole('USER')")
i changed it.

2020-04-20 12:33 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +        return new ResponseEntity<>(HttpStatus.NOT_FOUND);
Hmm, you are actually right here, but as you mentioned you should leave `NO_CONTENT` instead changing it to `NOT_FOUND`

2020-04-20 12:34 UTC, rbobko93 approved these changes
Accept this one last thing and I think we are ready to merge.

2020-04-20 12:34 UTC, rbobko93 commented on src/main/java/com/tstepnik/planner/controller/UserController.java
> +        return new ResponseEntity<>(HttpStatus.OK);
```suggestion
        return new ResponseEntity<>(HttpStatus. NO_CONTENT);
```

2020-04-20 14:33 UTC, merged